parameters:
#    jy_accede_api.example.class: JyAccede\Bundle\APIBundle\Example

services:
#    jy_accede_api.example:
#        class: %jy_accede_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
