parameters:
#    jy_accede_location.example.class: JyAccede\Bundle\LocationBundle\Example

services:
#    jy_accede_location.example:
#        class: %jy_accede_location.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
